apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitor-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visitor
  template:
    metadata:
      labels:
        app: visitor
    spec:
      containers:
      - name: visitor
        image: msalihogun/visitor-counter:{{ .IMAGE_TAG }}
	imagePullPolicy: Always
        ports:
        - containerPort: 3000
